"""Send application materials via Resend."""

import logging
import resend
from config import RESEND_API_KEY, RESEND_FROM, RESEND_TO

logger = logging.getLogger(__name__)


def is_configured() -> bool:
    return bool(RESEND_API_KEY and RESEND_TO)


def _analysis_to_html(job_info: dict, analysis: dict) -> str:
    """Render the fit analysis as an HTML email section."""
    score = analysis.get("fit_score", 0)
    color = "#22c55e" if score >= 80 else ("#f59e0b" if score >= 70 else "#ef4444")

    bd = analysis.get("score_breakdown") or {}

    def ul(items: list, key: str = None) -> str:
        if not items:
            return "<i>None</i>"
        rows = []
        for item in items:
            if key:
                rows.append(f"<li>{item.get(key, '')}</li>")
            else:
                rows.append(f"<li>{item}</li>")
        return "<ul style='margin:4px 0;padding-left:18px'>" + "".join(rows) + "</ul>"

    strengths_html = "".join(
        f"<li><b>{s.get('point','')}</b> — {s.get('evidence','')}</li>"
        for s in analysis.get("strengths", [])
    )
    weaknesses_html = "".join(
        f"<li><b>{w.get('point','')}</b> — {w.get('impact','')}</li>"
        for w in analysis.get("weaknesses", [])
    )
    prefs_html = "".join(
        f"<li>{p.get('preference','')} — <b>{p.get('match','')}</b>: {p.get('notes','')}</li>"
        for p in analysis.get("preference_alignment", [])
    )

    sections = [
        f"<h1 style='margin-bottom:4px'>{job_info.get('role')} at {job_info.get('company')}</h1>",
        f"<p style='color:#555'>{job_info.get('location')} · {job_info.get('employment_type')} · "
        f"Salary: {job_info.get('salary') or 'not specified'}</p>",
        f"<hr>",

        f"<h2 style='color:{color}'>Fit score: {score}/100</h2>",
        f"<p>{analysis.get('score_rationale','')}</p>",

        f"<table style='border-collapse:collapse;width:100%;max-width:400px;margin-bottom:16px'>",
        f"<tr><td style='padding:4px 8px;background:#f3f4f6'>Must-have requirements</td>"
        f"<td style='padding:4px 8px;text-align:right'>{bd.get('must_have_requirements',0)}/40</td></tr>",
        f"<tr><td style='padding:4px 8px'>Experience &amp; seniority</td>"
        f"<td style='padding:4px 8px;text-align:right'>{bd.get('experience_seniority',0)}/30</td></tr>",
        f"<tr><td style='padding:4px 8px;background:#f3f4f6'>Preferences &amp; logistics</td>"
        f"<td style='padding:4px 8px;text-align:right'>{bd.get('preferences_logistics',0)}/20</td></tr>",
        f"<tr><td style='padding:4px 8px'>Responsibilities &amp; bonus</td>"
        f"<td style='padding:4px 8px;text-align:right'>{bd.get('responsibilities_nice_to_have',0)}/10</td></tr>",
        f"</table>",
    ]

    if analysis.get("dealbreakers"):
        sections += [
            "<h3 style='color:#ef4444'>⛔ Dealbreakers (score capped at 49)</h3>",
            ul(analysis["dealbreakers"]),
        ]

    if analysis.get("job_inconsistencies"):
        sections += [
            "<h3>🔀 Job description inconsistencies</h3>",
            ul(analysis["job_inconsistencies"]),
        ]

    sections += [
        "<h3>✅ Strengths</h3>",
        f"<ul style='margin:4px 0;padding-left:18px'>{strengths_html}</ul>",
        "<h3>⚠️ Weaknesses</h3>",
        f"<ul style='margin:4px 0;padding-left:18px'>{weaknesses_html}</ul>",
    ]

    if analysis.get("red_flags"):
        sections += ["<h3>🚩 Red flags</h3>", ul(analysis["red_flags"])]

    sections += [
        "<h3>🎯 Preference alignment</h3>",
        f"<ul style='margin:4px 0;padding-left:18px'>{prefs_html}</ul>",
        "<h3>💡 Opportunities</h3>",
        ul(analysis.get("opportunities", [])),
        "<h3>📝 Recommendation</h3>",
        f"<p>{analysis.get('recommendation','')}</p>",
        "<h3>🔧 Improvement suggestions</h3>",
        ul(analysis.get("improvement_suggestions", [])),
        "<hr>",
        "<p style='color:#888;font-size:12px'>Generated by Job Fit Bot · "
        "Review the CV before sending — confirm all facts are accurate.</p>",
    ]

    return "\n".join(sections)


def send_application_email(
    role: str,
    company: str,
    fit_score: int,
    attachments: list[tuple[str, bytes]],
    job_info: dict | None = None,
    analysis: dict | None = None,
    to_address: str | None = None,
) -> None:
    """Send the full analysis + PDFs via Resend. Raises on failure."""
    resend.api_key = RESEND_API_KEY

    recipient = to_address or RESEND_TO
    if not recipient:
        raise ValueError("No recipient address — set RESEND_TO in .env or provide an address.")

    filenames = ", ".join(f for f, _ in attachments)
    logger.info("Sending email to %s — %s", recipient, filenames)

    html = _analysis_to_html(job_info or {}, analysis or {}) if (job_info and analysis) else (
        f"<h2>{role} at {company}</h2>"
        f"<p>Fit score: <strong>{fit_score}/100</strong></p>"
        f"<p>Application materials attached.</p>"
    )

    params: resend.Emails.SendParams = {
        "from": f"MakeTheCut <{RESEND_FROM}>",
        "to": [recipient],
        "subject": f"Make The Cut - Job Fit Analysis: {role} at {company} — {fit_score}/100",
        "html": html,
        "attachments": [
            {"filename": filename, "content": list(content)}
            for filename, content in attachments
        ],
    }

    response = resend.Emails.send(params)
    logger.info("Resend response: %s", response)
